language: "perl"
perl:
  - "5.18"
  - "5.16"

before_install:
    - git clone git://github.com/haarg/perl-travis-helper
    - source perl-travis-helper/init
    - build-perl
    - perl -V
    - build-dist
    - cd $BUILD_DIR

install:
    - cpanm --notest Cache::FastMmap::Tie Devel::Cover Devel::Cover::Report::Coveralls
    - cpanm --quiet --notest --installdeps .

script:
   - cd deferrer
   - perl Makefile.PL
   - make test
   - cover

  after_success:
    - cover -report coveralls
