language: "perl"
perl:
  - "5.22"
  - "5.16"

before_install:
    - cpanm --notest Cache::FastMmap::Tie
install:
    - cpanm --notest Devel::Cover Devel::Cover::Report::Coveralls Test::Script
script:
   - cd deferrer
   - perl Makefile.PL
   - make test
   - cover
after_success:
    - cover -report coveralls
