language: "perl"
perl:
  - "5.22"
  - "5.16"

before_install:
    - cpanm --notest Cache::FastMmap::Tie

install:
   - cpanm Devel::Cover
script:
   - cd deferrer
   - perl Makefile.PL
   - make test

